<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

$html = '<html><head><style>body { font-family: "Times New Roman", Times, serif; line-height: 1.6; padding: 20px; } h1 { font-family: "Times New Roman", Times, serif; text-align: center; margin-bottom: 5px; } p.sub {font-family: "Times New Roman", Times, serif; text-align: center; color: #555; margin-top: 0;} h2 { color: #333; margin-top: 25px; border-bottom: 1px solid #ccc; padding-bottom: 5px;} .content { margin: 20px; }</style></head><body><h1>Buku Manual Penggunaan SIBHP</h1><p class="sub">(Sistem Informasi Pengajuan Barang Habis Pakai)</p><hr><div class="content"><h2>1. Tujuan Dokumen (Pendahuluan)</h2><p>Dokumen Perancangan Awal dan Manual ini memuat spesifikasi tata cara penggunaan purwarupa Sistem Informasi Pengajuan Barang Habis Pakai (SIBHP) untuk memfasilitasi kebutuhan logistik seperti ATK dan sarana lain di instansi.</p><h2>2. Alur Penggunaan (Bagi Pegawai Biasa)</h2><ul><li>Masuk ke dalam sistem menggunakan otentikasi (seperti NIP dan Sandi) Anda.</li><li>Pilih modul <b>Permintaan Barang</b> pada navigasi sistem.</li><li>Klik tombol untuk memasukkan <b>Permintaan Baru</b>.</li><li>Pilih daftar barang inventaris, masukkan jumlah angka kuantitas, dan cantumkan alasan.</li><li>Simpan hasil pengajuan. Status draf Anda akan menjadi <i>"Menunggu Persetujuan"</i>.</li><li>Apabila disetujui, kunjungi Admin dan tunjukkan <b>Bukti Digital</b> untuk klaim.</li></ul><h2>3. Alur Penggunaan (Bagi Administrator)</h2><ul><li>Administrator mengawasi daftar ajuan melalui dasbor panel.</li><li>Memverifikasi silang ketersediaan barang. Jika lulus verifikasi, permintaan tersebut dapat disetujui.</li><li>Aksi Persetujuan akan men-<i>trigger</i> fungsi sistem untuk otomatis mengkalibrasi/memotong sisa stok gudang.</li><li>Administrator mencetak <b>Struk Tanda Bukti</b> (Thermal) sebagai validasi final.</li><li>Admin merekap barang kiriman (suplaI) ke dalam modul <b>Barang Masuk</b>.</li></ul><h2>4. Catatan Perancangan Awal</h2><p>Buku manual ini dibuat berdampingan dengan sketsa model ERD dan Usecase untuk mengakomodasi fase awal Software Development Life Cycle (SDLC).</p></div></body></html>';

app('dompdf.wrapper')->loadHTML($html)->save('c:\xampp\htdocs\sibhpujikom\dokumen_perancangan\Manual_Book_SIBHP.pdf');
echo "PDF berhasil dibuat!\n";
